spring:
  application:
    name: bus-inventory-service
server:
  port: 8086
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transithub}?currentSchema=bus_schema
    username: ${DB_USERNAME:transithub}
    password: ${DB_PASSWORD:TransitHub@2024}
  jpa:
    properties:
      hibernate:
        default_schema: bus_schema
