spring:
  application:
    name: notification-service
server:
  port: 8097
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:Mongo@2024@localhost:27017/transithub?authSource=admin}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:4566}
