spring:
  application:
    name: payment-service
server:
  port: 8094
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transithub}?currentSchema=payment_schema
    username: ${DB_USERNAME:transithub}
    password: ${DB_PASSWORD:TransitHub@2024}
  jpa:
    properties:
      hibernate:
        default_schema: payment_schema
