apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-registry.fullname" . }}
  labels:
    app: {{ include "service-registry.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "service-registry.name" . }}
