server: port: 8093
spring:
  application: name: inventory-lock-service
  redis:
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:Redis@2024}
eureka: client: service-url: defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
