apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  labels:
    app: {{ include "user-service.name" . }}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  EUREKA_URI: "http://service-registry:8761/eureka"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  DB_URL: "jdbc:postgresql://postgres:5432/transithub"
  MONGO_URI: "mongodb://mongodb:27017/transithub"
  REDIS_URI: "redis://redis:6379"
  AWS_S3_ENDPOINT: "http://localstack:4566"
  AWS_REGION: "us-east-1"
